name: ecosys_safety
description: Ecosys Safety.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  accordion: ^2.5.1
  #animate_do: ^3.0.2
  #animate_icons: ^2.0.0
  #animated_text_kit: ^4.2.2
  awesome_dialog: ^3.0.2
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  #carousel_slider: ^4.2.1
  custom_pop_up_menu: ^1.2.4
  dio: ^5.2.1+1
  #dotted_line: ^3.1.0
  dropdown_button2: ^2.0.0
  elegant_notification: ^1.8.1
  lottie: ^2.7.0
  equatable: ^2.0.5
  expandable: ^5.0.1
  file_picker: ^5.3.1
  file_saver: ^0.2.5
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.1.2
  flutter_colorpicker: ^1.0.3
  flutter_dotenv: ^5.0.2
  flutter_reorderable_list: ^1.3.1
  flutter_smart_dialog: ^4.9.0+6
  flutter_svg: ^2.0.7
  flutter_switch: ^0.3.2
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  http: ^0.13.5
  hydrated_bloc: ^9.1.0
  image_picker_web: ^3.0.0+1
  intl: ^0.18.0
  just_the_tooltip: ^0.0.12
  loading_animation_widget: ^1.2.0+4
  neopop: ^1.0.2
  number_paginator: ^0.2.3
  phosphor_flutter: ^2.0.0
  rotated_corner_decoration: ^2.1.0+1
  star_menu: ^3.1.4
  strings: ^0.2.2
  syncfusion_flutter_charts: ^23.1.44
  syncfusion_flutter_datagrid: ^23.1.44
  syncfusion_flutter_datepicker: ^23.1.44
  universal_html: ^2.2.3
  uuid: ^3.0.7
  webview_flutter:
  webview_flutter_web:
  web_smooth_scroll: ^1.1.0
  printing: ^5.6.0
  d_chart: ^2.6.2
  url_launcher: ^6.1.14
  connectivity_plus: ^5.0.1
  font_awesome_flutter: ^10.6.0
  toastification: ^0.0.3
  form_builder_validators: ^9.0.0
  flutter_form_builder: ^9.0.0
  select2dot1: ^2.0.7
  drag_and_drop_lists: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.png
    - envs/env.dev
    - envs/env.uat
    - envs/env.production

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/montserrat.ttf